name: "Tests"

on:
  push:
    paths:
      - ".github/**/*"
      - "Taskfile.yml"
      - "src/*"
      - "src/**/*"
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-task@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - run: ./gradlew buildPluginask
      - run: ./gradlew test

      - name: "Discord notification (not success)"
        uses: rjstone/discord-webhook-notify@v1
        if: "! success()"
        with:
          description: "⚠ Markowl Tests failed!"
          footer: "Eclipse Temurin v11"
          severity: error
          avatarUrl: https://pics.prcm.jp/dea0419/39581377/jpeg/39581377.jpeg
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: "Discord notification (success)"
        uses: rjstone/discord-webhook-notify@v1
        if: "success()"
        with:
          description: "✅ Markowl Tests passed!"
          footer: "Eclipse Temurin v11"
          severity: info
          avatarUrl: https://www.suruga-ya.jp/database/pics_light/game/871005085.jpg
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
